cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0000.txt > ../data/out/0000.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0001.txt > ../data/out/0001.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0002.txt > ../data/out/0002.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0003.txt > ../data/out/0003.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0004.txt > ../data/out/0004.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0005.txt > ../data/out/0005.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0006.txt > ../data/out/0006.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0007.txt > ../data/out/0007.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0008.txt > ../data/out/0008.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0009.txt > ../data/out/0009.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0010.txt > ../data/out/0010.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0011.txt > ../data/out/0011.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0012.txt > ../data/out/0012.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0013.txt > ../data/out/0013.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0014.txt > ../data/out/0014.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0015.txt > ../data/out/0015.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0016.txt > ../data/out/0016.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0017.txt > ../data/out/0017.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0018.txt > ../data/out/0018.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0019.txt > ../data/out/0019.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0020.txt > ../data/out/0020.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0021.txt > ../data/out/0021.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0022.txt > ../data/out/0022.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0023.txt > ../data/out/0023.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0024.txt > ../data/out/0024.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0025.txt > ../data/out/0025.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0026.txt > ../data/out/0026.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0027.txt > ../data/out/0027.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0028.txt > ../data/out/0028.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0029.txt > ../data/out/0029.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0030.txt > ../data/out/0030.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0031.txt > ../data/out/0031.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0032.txt > ../data/out/0032.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0033.txt > ../data/out/0033.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0034.txt > ../data/out/0034.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0035.txt > ../data/out/0035.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0036.txt > ../data/out/0036.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0037.txt > ../data/out/0037.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0038.txt > ../data/out/0038.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0039.txt > ../data/out/0039.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0040.txt > ../data/out/0040.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0041.txt > ../data/out/0041.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0042.txt > ../data/out/0042.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0043.txt > ../data/out/0043.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0044.txt > ../data/out/0044.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0045.txt > ../data/out/0045.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0046.txt > ../data/out/0046.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0047.txt > ../data/out/0047.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0048.txt > ../data/out/0048.txt
cargo run --release --bin tester "../visualstudio/Release/marathon_main.exe" < ../data/in/0049.txt > ../data/out/0049.txt
